const defaultLayout = [
  {
    "box-shadow": "0px 3px 6px #00000039;",
    "bt-positive-color": "#003438",
    "bt-positive-color-hover": "#287E84",
    "bt-positive-text-color": "#ffff",
    "bt-positive-text-color-hover": "#ffffff",
    "bt-negative-color": "#00646c",
    "bt-negative-color-hover": "#00646c",
    "bt-negative-text-color": "#ffff",
    "bt-negative-text-color-hover": "#ffffff",
    "default-color": "#0db8bc",
    "default-color-hover": "#069da2",
    "default-contrast-color": "#cb5151",
    "default-high-contrast-color": "#701B13",
    "font-color": "#ffffff",
    "font-color-hover": "#ffffff",
    "font-color-opposite": "#000000",
    "error-color": "#ce171f",
    "header-color": "#00646c",
    "header-font-color": "#ffff",

    //unused variables

    "box-shadow": "0px 3px 6px #00000029;",
    "bt-purchase-color": "#e0e566",
    "bt-purchase-color-hover": "#e0e566",
    "bt-purchase-text-color": "#204986",
    "bt-purchase-text-color-hover": "#204986",
    "card-background": "#ffffff",
    "card-background-hover": "#ffffff",
    "card-color-details": "#5a646e",
    "card-color-details-hover": "#5a646e",
    "card-color-price": "#231f20",
    "card-color-price-hover": "#231f20",
    "default-color-icons": "#231f20",
    "explore-block-color": "#ffffff",
    "explore-block-color-hover": "#ffffff",
    "explore-block-text-color": "#000000",
    "explore-block-text-color-hover": "#000000",
    "footer-background-color": "#e8e8e8",
    "footer-text-color": "#231f20",
    "footer-title-color": "#231f20",
    "footer-text-color-hover": "#231f20",
    "logo-img": "/images/cieloLogo.png",
    "negative-button-border": "transparent",
    "profile-card-color": "#ffffff",
    "profile-card-color-hover": "#00aeef",
    "title-color": "#231f20",
    "title-modal-color": "#ffffff",
    "menu-sandwich-body": "#ffffff",
    "menu-sandwich-header": "#ffffff",
    "input-border-color": "#204986",
    "input-border-color-hover": "#204986",
    "configurable-attributes-color": "#231F20",
    "configurable-attributes-color-hover": "#231F20",
    "configurable-attributes-bgcolor": "#ffffff",
    "configurable-attributes-bgcolor-hover": "##E5F7FE",
  },
];

export default defaultLayout;
