const multiLang = [
  {
    language: "en",
    data: {
      labels: {
        404: {
          label01: "Ops, page not founded",
          label02: "Que tal procurar um produto no marketplace?",
          labelCard01: "a partir de",
          labelCard02: "Produto indisponível",
          label03: "Produtos mais populares",
          button01: "Pesquisar",
        },

        addpaymentmethod: {
          buttonModal01: "CANCELAR",
          buttonModal02: "ADICIONAR",
          buttonModal03: "NÃO",
          buttonModal04: "SIM",
          button01: "VOLTAR",
          button02: "ADICIONAR",

          label01: "Minha Conta",
          label02: "Formas de pagamento",
          label03: "Cartão",
          label04: "Nenhum cartão cadastrado",
          labelModal01: "Adicionar Cartão",
          labelModal02: "Você deseja deletar o cartão com o final ",
          labelModal03: " da sua conta?",
          labelModal04:
            "Esta é uma ação que não terá como desfazer. Por favor confirme primeiro que você tem certeza que quer prosseguir com esta ação.",

          placeholderModal01: "Nome como está no cartão*",
          placeholdermodal02: "Número do cartão",
          placeholdermodal03: "Digite seu CPF/CNPJ (Apenas Números)",
          placeholdermodal04: "Validade MM/AA",
          placeholdermodal05: "Código de Segurança",
        },
        campaign: {
          button01: "Pesquisar",
          button02: "VER MAIS",
          button03: "LIMPAR PESQUISA ",

          label01: "Buscando por algo específico?",
          labelCard01: "a partir de",
          labelCard02: "Produto indisponível",
        },
        cart: {
          altImage01: "Carregando",
          button01: "ADICIONAR",
          buttonModal01: "CANCELAR",
          buttonModal02: "MUDAR",
          buttonModal03: "ADICIONAR",
          buttonModal04: "CADASTRAR NOVO ENDEREÇO",
          buttonModal05: "CADASTRAR ENDEREÇO",
          label01: "Carrinho de compras possui",
          label02: "USAR LOCALIZAÇÃO ATUAL",
          label03: "Você precisa ter um endereço padrão de entrega",
          label04: "Endereço de Entrega",
          labelModal01: "Mudar Endereço",
          labelModal02: "Nenhum endereço cadastrado",
          labelModal03: "OU",
          labelModal04: "Adicionar Endereço",
          labelModal05: " nº ",
          labelModal06: " CEP ",
          placeholderModal01: "Digite o cep",
          placeholderModal02: "Digite o apelido do endereço",
          placeholderModal03: "Rua, Avenida, Etc",
          placeholderModal04: "Número",
          placeholderModal05: "Digite o complemento",
          placeholderModal06: "Digite o bairro",
          placeholderModal07: "Digite a cidade",
          placeholderModal08: "Digite o estado",
          placeholderModal09: "Telefone/Celular",
        },
        cartEmpty: {},
        categories: {},
        contact: {},
        contentPages: {},
        findPromoters: {},
        footer: {
          label01: "MARKETPLACE DEVELOPED BY",
        },
        header: {
          buttonModal01: "Buscar Endereço",
          buttonModal02: "Remover localização atual",
          buttonModal03: "Usar localização atual",
          buttonModal04: "Voltar",
          buttonModal05: "Atualizar",
          buttonModal06: "Salvar",
          label01: "Português",
          label02: "Calculando para",
          label03: "Localização",
          label04: "Indefinida",
          label05: "Carrinho",
          label06: "Perfil",
          label07: "Shop by",
          label08: "Departments",
          label09: "Enviar para",
          label10: "Escolher uma localização",
          labelModal01: "Selecione o idioma do site",
          labelModal02: "Onde você quer receber o seu pedido?",
          labelModal03: "Adicionar novo endereço",
          labelModal04: "Ativado",
          labelModal05: "Desativado",
          labelModal06: "Localização atual",
          labelModal07: "Main menu",
          labelModal08: "Home",
          labelModal09: "Go to",
          languagesPack: [
            {
              name: "Brazilian Portuguese",
              slug: "pt_BR",
              image: "./images/flagBrazil.jpg",
              alt: "flag of Brazil",
            },
            {
              name: "Argentinian Spanish",
              slug: "es_AR",
              image: "./images/flagArgentina.jpg",
              alt: "flag of Argentina",
            },
            {
              name: "Spanish",
              slug: "es",
              image: "./images/flagSpain.jpg",
              alt: "flag of Spain",
            },
            {
              name: "English",
              slug: "en",
              image: "./images/flagEngland.jpg",
              alt: "flag of England",
            },
          ],
          label01: "English",
          labelModal01: "Select the language of site",
          placeholder01: "I'm searching for...",
        },
        home: {},
        inspire: {},
        likes: {},
        login: {},
        orderData: {},
        orderHistory: {},
        otherOffers: {},
        passwordReset: {},
        payment: {},
        photobook: {},
        product: {},
        productSeller: {},
        profile: {
          button01: "Sign out",
          label01: "Edit profile",
          label02: "Shipping address",
          label03: "Company info",
          label04: "Access levels",
          label05: "Orders history",
          label06: "Payment methods",
          label07: "Checking Account",
          languagesPack: [
            {
              name: "Brazilian Portuguese",
              slug: "pt_BR",
              image: "./images/flagBrazil.jpg",
              alt: "flag of Brazil",
            },
            {
              name: "Argentinian Spanish",
              slug: "es_AR",
              image: "./images/flagArgentina.jpg",
              alt: "flag of Argentina",
            },
            {
              name: "Spanish",
              slug: "es",
              image: "./images/flagSpain.jpg",
              alt: "flag of Spain",
            },
            {
              name: "English",
              slug: "en",
              image: "./images/flagEngland.jpg",
              alt: "flag of England",
            },
          ],
        },
        profileAddresses: {},
        profileEdit: {},
        profilePublicPromoter: {},
        publicList: {},
        publicPhotobook: {},
        register: {},
        search: {},
        searchCategory: {},
        seeMore: {},
        seller: {},
        tempCart: {},
        tempRegister: {},
        wishlist: {},
        wishlistProducts: {},
      },
      notifications: {
        404: {},

        addpaymentmethod: {
          notificationError01: "Sua sessão expirou, faça o login novamente",
        },
        campaign: {
          notificationError01: "Erro ao carregar página de campanha",
          notificationError02: "Página de campanha não encontrada",
        },
        cart: {
          notificationError01: "Sua sessão expirou, faça o login novamente",
          notificationError02: "Cep inválido",
          notificationError03:
            "Você não possuí nenhum endereço padrão de entrega, altere em seu perfil.",
          notificationError04: "Cupom inválido",
          notificationError05:
            "Termos de aceite não encontrados, entre em contato com o administrador do sistema",
          notificationError06:
            "Faça sua geolocalização e entre no carrinho novamente para visulizá-lo",
          notificationSuccess01: "Você alterou seu endereço padrão de entrega.",
          notificationSuccess02: "Item removido com sucesso.",
          notificationSuccess03: "Cupom adicionado com sucesso!",
          notificationSuccess04: "Cupom removido com sucesso!",
          notificationSuccess05: "Quantidade de produto alterada!",
          notificationSuccess06: "Seu carrinho foi limpo!",
        },
        cartEmpty: {},
        categories: {},
        contact: {},
        contentPages: {},
        findPromoters: {},
        footer: {},
        header: {},
        home: {},
        inspire: {},
        likes: {},
        login: {},
        orderData: {},
        orderHistory: {},
        otherOffers: {},
        passwordReset: {},
        payment: {},
        photobook: {},
        product: {},
        productSeller: {},
        profile: {},
        profileAddresses: {},
        profileEdit: {},
        profilePublicPromoter: {},
        publicList: {},
        publicPhotobook: {},
        register: {},
        search: {},
        searchCategory: {},
        seeMore: {},
        seller: {},
        tempCart: {},
        tempRegister: {},
        wishlist: {},
        wishlistProducts: {},
      },
    },
  },
  {
    language: "pt_BR",
    data: {
      labels: {
        404: {
          label01: "Ops, página não encontrada",
          label02: "Que tal procurar um produto no marketplace?",
          labelCard01: "a partir de",
          labelCard02: "Produto indisponível",
          label03: "Produtos mais populares",
          button01: "Pesquisar",
        },

        addpaymentmethod: {
          buttonModal01: "CANCELAR",
          buttonModal02: "ADICIONAR",
          buttonModal03: "NÃO",
          buttonModal04: "SIM",
          button01: "VOLTAR",
          button02: "ADICIONAR",

          label01: "Minha Conta",
          label02: "Formas de pagamento",
          label03: "Cartão",
          label04: "Nenhum cartão cadastrado",
          labelModal01: "Adicionar Cartão",
          labelModal02: "Você deseja deletar o cartão com o final ",
          labelModal03: " da sua conta?",
          labelModal04:
            "Esta é uma ação que não terá como desfazer. Por favor confirme primeiro que você tem certeza que quer prosseguir com esta ação.",

          placeholderModal01: "Nome como está no cartão*",
          placeholdermodal02: "Número do cartão",
          placeholdermodal03: "Digite seu CPF/CNPJ (Apenas Números)",
          placeholdermodal04: "Validade MM/AA",
          placeholdermodal05: "Código de Segurança",
        },
        campaign: {
          button01: "Pesquisar",
          button02: "VER MAIS",
          button03: "LIMPAR PESQUISA ",

          label01: "Buscando por algo específico?",
          labelCard01: "a partir de",
          labelCard02: "Produto indisponível",
        },
        cart: {
          altImage01: "Carregando",
          button01: "ADICIONAR",
          button02: "MUDAR",
          button03: "LIMPAR CARRINHO",
          button04: "CONTINUAR COMPRANDO",
          button05: "REMOVER",
          button06: "APLICAR",
          button07: "SEGUIR PARA O CATÁLOGO",
          buttonModal01: "CANCELAR",
          buttonModal02: "MUDAR",
          buttonModal03: "ADICIONAR",
          buttonModal04: "CADASTRAR NOVO ENDEREÇO",
          buttonModal05: "CADASTRAR ENDEREÇO",
          label01: "Carrinho de compras possui",
          label02: "USAR LOCALIZAÇÃO ATUAL",
          label03: "Você precisa ter um endereço padrão de entrega",
          label04: "Endereço de Entrega",
          label05: "Vendido e entregue por ",
          label06:
            "Desculpa, esse lojista não faz entregas neste CEP. Tente outra loja.",
          label07: "Selecione um frete",
          label08: "INDISPONÍVEL",
          label09: "Receba em casa",
          label10: "Escolher uma transportadora",
          label11: "dias",
          label12: "FRETE GRÁTIS",
          label13: "INDISPONÍVEL",
          label14: "Retirar na loja",
          label15: "Buscar na loja",
          label16: "Resumo da compra",
          label17: "Produtos",
          label18: "Frete",
          label19: "Cupom:",
          label20: "Desconto Cupom",
          label21: "Desconto",
          label22: "Total",
          label23:
            "Seu carrinho está vazio vá para o catálogo para adicionar produtos",
          labelModal01: "Mudar Endereço",
          labelModal02: "Nenhum endereço cadastrado",
          labelModal03: "OU",
          labelModal04: "Adicionar Endereço",
          labelModal05: " nº ",
          labelModal06: " CEP ",
          placeholderModal01: "Digite o cep",
          placeholderModal02: "Digite o apelido do endereço",
          placeholderModal03: "Rua, Avenida, Etc",
          placeholderModal04: "Número",
          placeholderModal05: "Digite o complemento",
          placeholderModal06: "Digite o bairro",
          placeholderModal07: "Digite a cidade",
          placeholderModal08: "Digite o estado",
          placeholderModal09: "Telefone/Celular",
        },
        cartEmpty: {},
        categories: {},
        contact: {},
        contentPages: {},
        findPromoters: {},
        footer: {
          label01: "MARKETPLACE DESENVOLVIDO POR",
          label02: "Quero vender na",
          label03: "ATENDIMENTO",
          label04: "Fale Conosco",
          label05: "DÚVIDAS",
          label06: "Central de Atendimento",
          label07: "Política de Devoluções",
          label08: "Política de Reembolso",
          label09: "Política de Privacidade",
          label10: "Cookies",
          label11: "NOSSAS REDES SOCIAIS",
          label12: "FORMAS DE PAGAMENTO",
          label13:
            "Formas de pagamento aceitas: cartões de crédito (Mastercard, Visa, Hipercard, Elo, Amex) e Boleto bancário à vista.",

          label14: "SELO E SEGURANÇA",
        },
        header: {
          buttonModal01: "Buscar Endereço",
          buttonModal02: "Remover localização atual",
          buttonModal03: "Usar localização atual",
          buttonModal04: "Voltar",
          buttonModal05: "Atualizar",
          buttonModal06: "Salvar",
          label01: "Português",
          label02: "Calculando para",
          label03: "Localização",
          label04: "Indefinida",
          label05: "Carrinho",
          label06: "Perfil",
          label07: "Comprar por",
          label08: "Departamentos",
          label09: "Enviar para",
          label10: "Escolher uma localização",
          labelModal01: "Selecione o idioma do site",
          labelModal02: "Onde você quer receber o seu pedido?",
          labelModal03: "Adicionar novo endereço",
          labelModal04: "Ativado",
          labelModal05: "Desativado",
          labelModal06: "Localização atual",
          labelModal07: "Menu Principal",
          labelModal08: "Início",
          languagesPack: [
            {
              name: "Português Brasileiro",
              slug: "pt_BR",
              image: "./images/flagBrazil.jpg",
              alt: "bandeira do Brasil",
            },
            {
              name: "Espanhol Argentino",
              slug: "es_AR",
              image: "./images/flagArgentina.jpg",
              alt: "bandeira da Argentina",
            },
            {
              name: "Espanhol",
              slug: "es",
              image: "./images/flagSpain.jpg",
              alt: "bandeira da Espanha",
            },
            {
              name: "Inglês",
              slug: "en",
              image: "./images/flagEngland.jpg",
              alt: "bandeira do Reino Unido",
            },
          ],

          optionModal01: "Endereço Ativado",
          optionModal02: "Endereço Desativado",
          placeholder01: "Estou procurando por...",
          placeholderModal01: "Rua*",
          placeholderModal02: "Apelido do endereço (ex: Minha Casa)*",
          placeholderModal03: "Telefone/Celular*",
          placeholderModal04: "Número*",
          placeholderModal05: "Bairro*",
          placeholderModal06: "Cidade*",
          placeholderModal07: "Estado*",
          placeholderModal08: "Complemento",
        },
        home: {},
        inspire: {},
        likes: {},
        login: {},
        orderData: {},
        orderHistory: {},
        otherOffers: {},
        passwordReset: {},
        payment: {},
        photobook: {},
        product: {},
        productSeller: {},
        profile: {
          button01: "VOLTAR",
          label01: "Editar perfil",
          label02: "Endereços para entrega",
          label03: "Dados da empresa",
          label04: "Níveis de acesso",
          label05: "Histórico de pedidos",
          label06: "Formas de pagamento",
          label07: "Conta corrente",
          languagesPack: [
            {
              name: "Brazilian Portuguese",
              slug: "pt_BR",
              image: "./images/flagBrazil.jpg",
              alt: "flag of Brazil",
            },
            {
              name: "Argentinian Spanish",
              slug: "es_AR",
              image: "./images/flagArgentina.jpg",
              alt: "flag of Argentina",
            },
            {
              name: "Spanish",
              slug: "es",
              image: "./images/flagSpain.jpg",
              alt: "flag of Spain",
            },
            {
              name: "English",
              slug: "en",
              image: "./images/flagEngland.jpg",
              alt: "flag of England",
            },
          ],
        },
        profileAddresses: {},
        profileEdit: {},
        profilePublicPromoter: {},
        publicList: {},
        publicPhotobook: {},
        register: {},
        search: {},
        searchCategory: {},
        seeMore: {},
        seller: {},
        tempCart: {},
        tempRegister: {},
        wishlist: {},
        wishlistProducts: {},
      },
      notifications: {
        404: {},

        addpaymentmethod: {
          notificationError01: "Sua sessão expirou, faça o login novamente",
        },
        campaign: {
          notificationError01: "Erro ao carregar página de campanha",
          notificationError02: "Página de campanha não encontrada",
        },
        cart: {
          notificationError01: "Sua sessão expirou, faça o login novamente",
          notificationError02: "Cep inválido",
          notificationError03:
            "Você não possuí nenhum endereço padrão de entrega, altere em seu perfil.",
          notificationError04: "Cupom inválido",
          notificationError05:
            "Termos de aceite não encontrados, entre em contato com o administrador do sistema",
          notificationError06:
            "Faça sua geolocalização e entre no carrinho novamente para visulizá-lo",
          notificationSuccess01: "Você alterou seu endereço padrão de entrega.",
          notificationSuccess02: "Item removido com sucesso.",
          notificationSuccess03: "Cupom adicionado com sucesso!",
          notificationSuccess04: "Cupom removido com sucesso!",
          notificationSuccess05: "Quantidade de produto alterada!",
          notificationSuccess06: "Seu carrinho foi limpo!",
        },
        cartEmpty: {},
        categories: {},
        contact: {},
        contentPages: {},
        findPromoters: {},
        footer: {},
        header: {
          notificationSuccess01:
            "Você agora está geolocalizado para as melhores ofertas.",
          notificationError01: "Cep Inválido",
          notificationError02: "Sua sessão expirou, faça o login novamente",
        },
        home: {},
        inspire: {},
        likes: {},
        login: {},
        orderData: {},
        orderHistory: {},
        otherOffers: {},
        passwordReset: {},
        payment: {},
        photobook: {},
        product: {},
        productSeller: {},
        profile: {},
        profileAddresses: {},
        profileEdit: {},
        profilePublicPromoter: {},
        publicList: {},
        publicPhotobook: {},
        register: {},
        search: {},
        searchCategory: {},
        seeMore: {},
        seller: {},
        tempCart: {},
        tempRegister: {},
        wishlist: {},
        wishlistProducts: {},
      },
    },
  },
];

export default multiLang;
